// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package Melkweg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MPacket struct {
	Iv                   []byte   `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	Port                 uint32   `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`
	Flags                uint32   `protobuf:"varint,11,opt,name=flags,proto3" json:"flags,omitempty"`
	Data                 []byte   `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	Padding              []byte   `protobuf:"bytes,13,opt,name=padding,proto3" json:"padding,omitempty"`
	User                 string   `protobuf:"bytes,20,opt,name=user,proto3" json:"user,omitempty"`
	Secret               string   `protobuf:"bytes,21,opt,name=secret,proto3" json:"secret,omitempty"`
	ClientTime           uint64   `protobuf:"varint,30,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	ServerTime           uint64   `protobuf:"varint,31,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MPacket) Reset()         { *m = MPacket{} }
func (m *MPacket) String() string { return proto.CompactTextString(m) }
func (*MPacket) ProtoMessage()    {}
func (*MPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_packet_8cdc48e51c805027, []int{0}
}
func (m *MPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MPacket.Unmarshal(m, b)
}
func (m *MPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MPacket.Marshal(b, m, deterministic)
}
func (dst *MPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MPacket.Merge(dst, src)
}
func (m *MPacket) XXX_Size() int {
	return xxx_messageInfo_MPacket.Size(m)
}
func (m *MPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_MPacket.DiscardUnknown(m)
}

var xxx_messageInfo_MPacket proto.InternalMessageInfo

func (m *MPacket) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *MPacket) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *MPacket) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *MPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MPacket) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

func (m *MPacket) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MPacket) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *MPacket) GetClientTime() uint64 {
	if m != nil {
		return m.ClientTime
	}
	return 0
}

func (m *MPacket) GetServerTime() uint64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func init() {
	proto.RegisterType((*MPacket)(nil), "Melkweg.MPacket")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_packet_8cdc48e51c805027) }

var fileDescriptor_packet_8cdc48e51c805027 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x4e, 0x85, 0x30,
	0x10, 0x45, 0x83, 0x41, 0x88, 0x03, 0xb8, 0x98, 0xa0, 0x99, 0x95, 0x18, 0x57, 0xae, 0xdc, 0xf8,
	0x1d, 0x24, 0xa6, 0x71, 0x6f, 0x2a, 0x8c, 0xa4, 0x01, 0xa1, 0x29, 0x15, 0x3f, 0xf7, 0xfd, 0xca,
	0x6b, 0xa7, 0xef, 0xed, 0xee, 0x3d, 0x73, 0xee, 0x62, 0xa0, 0xb6, 0x7a, 0x98, 0xd9, 0xbf, 0x59,
	0xb7, 0xf9, 0x0d, 0xcb, 0x9e, 0x97, 0xf9, 0x9f, 0xa7, 0x97, 0x53, 0x06, 0x65, 0xff, 0x21, 0x27,
	0xbc, 0x87, 0x1b, 0x73, 0x50, 0xf6, 0x9c, 0xbd, 0xd6, 0x2a, 0x24, 0x44, 0xc8, 0xed, 0xe6, 0x3c,
	0x41, 0x20, 0x8d, 0x92, 0x8c, 0x2d, 0xdc, 0xfe, 0x2c, 0x7a, 0xda, 0xa9, 0x12, 0x98, 0x4a, 0x34,
	0x47, 0xed, 0x35, 0xd5, 0xb2, 0x95, 0x8c, 0x04, 0xa5, 0xd5, 0xe3, 0x68, 0xd6, 0x89, 0x1a, 0xc1,
	0xd7, 0x1a, 0xed, 0xbf, 0x9d, 0x1d, 0xb5, 0x01, 0xdf, 0x29, 0xc9, 0xf8, 0x08, 0xc5, 0xce, 0x83,
	0x63, 0x4f, 0x0f, 0x42, 0x2f, 0x0d, 0x3b, 0xa8, 0x86, 0xc5, 0xf0, 0xea, 0xbf, 0xbc, 0xf9, 0x65,
	0x7a, 0x0a, 0xc7, 0x5c, 0x41, 0x42, 0x9f, 0x81, 0x44, 0x21, 0xec, 0x0f, 0x76, 0x49, 0xe8, 0x92,
	0x90, 0x50, 0x14, 0xbe, 0x0b, 0xf9, 0xf8, 0xfd, 0x1c, 0x00, 0x00, 0xff, 0xff, 0x29, 0x83, 0xa9,
	0xd5, 0x01, 0x01, 0x00, 0x00,
}
